require("dotenv").config();

const {
  PORT = 5000,
  MONGODB_URI,
  JWT_SECRET,
  REFRESH_TOKEN_SECRET,
  NODEMAILER_EMAIL,
  NODEMAILER_PASS,
  TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN,
  TWILIO_PHONE_NUMBER,
  FRONTEND_URL
} = process.env;

module.exports = {
  PORT,
  MONGODB_URI,
  JWT_SECRET,
  REFRESH_TOKEN_SECRET,
  NODEMAILER_EMAIL,
  NODEMAILER_PASS,
  TWILIO_ACCOUNT_SID,
  TWILIO_AUTH_TOKEN,
  TWILIO_PHONE_NUMBER,
  FRONTEND_URL
};